spring:
  main:
      allow-circular-references: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
  application:
    name: map
  datasource:
    url: ${DB}
    username: ${US}
    password: ${PAS}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
geoapify:
  secret: ${GEOAPIFY_SECRET}
server:
  port: 8081
saving_dir: ${SAVING_DIR}
