spring:
  main:
      allow-circular-references: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
  application:
    name: map
  datasource:
    url: jdbc:postgresql://dpg-d186vd8gjchc73drhs6g-a:5432/diplom_d21j
    username: eugene
    password: 6FC3SdEOm8216qwCi7JbPLmank9IdjMw
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG

geoapify:
  secret: ${GEOAPIFY_SECRET}
server:
  port: ${PORT:8080}
  servlet:
    context-path: /backend
saving_dir: ${SAVING_DIR}


